import 'package:hivorr/integrations/payment_gateways/models/payment_models.dart';

/// The provider-agnostic payment gateway contract.
///
/// `lib/systems/finance/` (EP-02-13/14/16) must interact only with this
/// interface (plus [PaymentGatewayFactory]) and never import concrete
/// adapters (ARCHITECTURE.md:151-152). Concrete providers implement this
/// contract and map their proprietary wire formats internally.
///
/// ## Amount normalization
/// Every method accepts/returns the neutral [Amount] in **minor units**
/// (kobo/pesewas/cents). Adapters convert internally: Paystack quotes kobo,
/// Flutterwave quotes major units — both unify here, preventing 100x bugs.
///
/// ## Idempotency
/// [reference] is the shared idempotency key (UUID v4), generated by the
/// caller or factory — never provider-generated alone. A retried
/// `initializePayment` with the same [reference] yields a `conflict`
/// (PLT005) the caller treats as "already initialized", not a duplicate charge.
///
/// ## Webhook is notification, verify is truth
/// [parseWebhookEvent] reports a notification status only. Before any ledger
/// mutation, downstream must re-fetch truth via [verifyPayment] /
/// [verifyTransfer]. Webhook signatures must be checked with
/// [verifyWebhookSignature] before trusting the payload; a mismatch fails
/// closed with `forbidden` (PLT002).
///
/// ## Error contract
/// Every method throws only [ApiException] (via the injected
/// `ApiExceptionMapper` for transport errors, or a constructed `ApiException`
/// for provider logical errors). Raw `DioException` and provider JSON never
/// propagate.
abstract class PaymentGateway {
  /// The backing provider identity.
  PaymentProvider get provider;

  /// Initializes a payment and returns the hosted checkout URL.
  Future<PaymentInitializationResult> initializePayment(
    PaymentInitializationRequest request,
  );

  /// Verifies a payment by its [reference] (provider ref or transaction id).
  Future<PaymentVerificationResult> verifyPayment(String reference);

  /// Creates a transfer (payout) to a verified recipient.
  Future<TransferResult> createTransfer(TransferRequest request);

  /// Verifies a transfer by its [reference].
  Future<TransferResult> verifyTransfer(String reference);

  /// Refunds a previously completed transaction.
  Future<RefundResult> refundPayment(RefundRequest request);

  /// Parses a raw webhook body into a neutral [WebhookEvent].
  ///
  /// The returned [WebhookEvent.status] is a notification only — re-verify
  /// before any business action.
  WebhookEvent parseWebhookEvent(
    Map<String, dynamic> rawBody,
    Map<String, String> headers,
  );

  /// Validates the provider webhook signature for [rawBody].
  ///
  /// On mismatch, throws `ApiExceptionKind.forbidden` (PLT002) so callers
  /// fail closed and never process an unverified webhook.
  bool verifyWebhookSignature({
    required String rawBody,
    required String signatureHeader,
  });
}
